In [51]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [52]:
dataset=pd.read_csv('Churn_Modelling.csv')

# part 1-Data  Preprocessing

In [53]:
X=dataset.iloc[:,3:-1].values
y=dataset.iloc[:,-1].values

In [54]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
X[:,2]=le.fit_transform(X[:,2])

In [55]:
X[0]

array([619, 'France', 0, 42, 2, 0.0, 1, 1, 1, 101348.88], dtype=object)

In [56]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
X=np.array(ct.fit_transform(X))

In [57]:
X[0]

array([1.0, 0.0, 0.0, 619, 0, 42, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

In [58]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [59]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [60]:
X_train[0]

array([-1.01460667, -0.5698444 ,  1.74309049,  0.16958176, -1.09168714,
       -0.46460796,  0.00666099, -1.21571749,  0.8095029 ,  0.64259497,
       -1.03227043,  1.10643166])

# Building ANN

## Initializing ANN

In [61]:
ann=tf.keras.models.Sequential()

## Adding input layer and first hidden layer

In [62]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

## Adding second hidden layer

In [63]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

## adding output layer

In [64]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

# Training the ANN

## Compiling ANN

In [65]:
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

## Training the ANN on training dataset

In [66]:
ann.fit(X_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
250/250 [==============================] - 0s 904us/step - loss: 0.7294 - accuracy: 0.5400
Epoch 2/100
250/250 [==============================] - 0s 850us/step - loss: 0.6107 - accuracy: 0.8151
Epoch 3/100
250/250 [==============================] - 0s 963us/step - loss: 0.5657 - accuracy: 0.8180
Epoch 4/100
250/250 [==============================] - 0s 953us/step - loss: 0.5272 - accuracy: 0.8290
Epoch 5/100
250/250 [==============================] - 0s 974us/step - loss: 0.4917 - accuracy: 0.8395
Epoch 6/100
250/250 [==============================] - 0s 997us/step - loss: 0.4623 - accuracy: 0.8440
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4395 - accuracy: 0.8472
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4224 - accuracy: 0.8493
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4089 - accuracy: 0.8491
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3

## Making prediction on Test set and confusion matrix

In [67]:
y_pred=ann.predict(X_test)
y_pred=(y_pred>0.5)

In [68]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
score=accuracy_score(y_test,y_pred)

In [69]:
print(cm)

[[1521   74]
 [ 194  211]]


In [70]:
print(score)

0.866


## Making a prediction for new value
### creditScore : 600
### Geography: France
### Gender:Female
### age:40
### tenure:3
### balance:60000
### numofproducs:2
### hasCrCard:1
### IsActiveMember:1
### EstimatedSalary:50000

In [71]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))) #result in probabilty percentage as we have used SIGMOID funcion above

[[0.03989416]]


In [72]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))>0.5)

[[False]]


#### False: Employee will not leave the Bank
#### True: Employee will leave